services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8088:80"
    networks:
      - gsysnet

networks:
  gsysnet:
    external: true
