services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8088:80"
    networks:
      - gestionback_gsysnet

networks:
  gestionback_gsysnet:
    external: true
